### ISSUE TITLE
global fetch support still requires undici to be installed externally

### ISSUE THREAD

**Issue by lucaswerkmeister** [3846masa/http-cookie-agent#544]
## Describe the bug

According to the README, “`http-cookie-agent` supports global fetch since Node.js v18.2.0.” However, this is only true if `undici` is also available in `node_modules/`.

## To Reproduce

1. Create a blank project
2. Install only `tough-cookie` and `http-cookie-agent`
3. Run the [Node.js global fetch example code from the README](https://github.com/3846masa/http-cookie-agent/blob/ef7747518021f721bf77c744c50cd31322f57985/README.md#nodejs-global-fetch)

## Expected behavior

The  `fetch()` succeeds.

## Actual behavior

<details>
<summary>Error: cannot find module 'undici'</summary>

```
node:internal/modules/cjs/loader:1070
  const err = new Error(message);
              ^

Error: Cannot find module 'undici'
Require stack:
- /tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js
- /tmp/cookie/node_modules/http-cookie-agent/dist/undici/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js',
    '/tmp/cookie/node_modules/http-cookie-agent/dist/undici/index.js'
  ]
}

Node.js v20.3.0
```

</details>

## Code that reproduces the bug

The `README.md` example code, as linked above.

<details>
<summary>Example shell session</summary>

```
/tmp $ mkdir cookie && cd cookie

/tmp/cookie $ npm i tough-cookie http-cookie-agent

added 11 packages, and audited 12 packages in 496ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

/tmp/cookie $ cat >> index.mjs << 'EOF'
import { CookieJar } from 'tough-cookie';
import { CookieAgent } from 'http-cookie-agent/undici';

const jar = new CookieJar();
const agent = new CookieAgent({ cookies: { jar } });

await fetch('https://example.com', { dispatcher: agent });
EOF

/tmp/cookie $ node index.mjs 
node:internal/modules/cjs/loader:1070
  const err = new Error(message);
              ^

Error: Cannot find module 'undici'
Require stack:
- /tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js
- /tmp/cookie/node_modules/http-cookie-agent/dist/undici/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/cookie/node_modules/http-cookie-agent/dist/undici/cookie_agent.js',
    '/tmp/cookie/node_modules/http-cookie-agent/dist/undici/index.js'
  ]
}

Node.js v20.3.0
```

</details>

## Environments

- OS: Linux
- Node.js version: 20.3.0
- http-cookie-agent version: 5.0.4
- axios version: N/A
- tough-cookie version: 4.1.3

**Comment by lucaswerkmeister** [comment]
Note: I’m aware that it might not be possible to fix this issue at the moment. You need an `Agent` class to extend, and as far as I can tell, Node.js doesn’t expose anything from the internal undici copy other than the `fetch()` function itself, so getting the `Agent` class from an external undici in `node_modules/` might be the only option. But then this should at least be documented a bit more clearly in the README, imho.

**Comment by 3846masa** [comment]
Thanks for the report.

You need to install undici for using http-cookie-agent with Node.js global fetch.

This is documented in the `Install` section of the README.

https://github.com/3846masa/http-cookie-agent/blob/7fd485e71fdab50de3c72a5280a27ea48fecf4cd/README.md?plain=1#L22-L32

If you need additional information, please reopen the issue.

**Comment by lucaswerkmeister** [comment]
Apologies, I assumed that section only applied to Node versions prior to shipping built-in global fetch.
